### ISSUE TITLE
Medium Difficulty in Documentation is Impossible

### ISSUE THREAD

**Issue by CaiB** [Sanakan8472/copy-dialog-lunar-lander#1]
Hello,

I have encountered an issue that is causing this to be completely unplayable for me.
In `README.md`, the description of "Medium difficulty" explains that one should use a USB 2.0 flash drive, however the demo image shows a sustained copy speed more than double that of the theoretical maximum USB 2.0 transfer rate (60MB/s).

Jokes about unplayability aside, I love this concept. Nice work!

**Comment by Sanakan8472** [comment]
Hi @CaiB !
Thank you for your valuable feedback and enjoying the game.

I must admit, I didn't have a USB 2.0 stick at hand and instead faked the screenshot by just copying from a remote PC that I thought would result in a comparable uneven graph. I now realize my mistake and will strive for more convincing fraud in the future.
