### ISSUE TITLE
Game sometimes runs through windows above it

### ISSUE THREAD

**Issue by sammccants** [Sanakan8472/copy-dialog-lunar-lander#10]
As you can see in the below screenshot, there are instances where the game shows on top of windows you place in front of it, despite the copy dialog window being hidden. I'm sorry that I don't have more details; I haven't noticed what specific circumstances cause this to happen.

![lunar-lander-bug](https://user-images.githubusercontent.com/43344196/192139980-72209393-01e3-4a97-abcf-14241536ccf8.png)

I'm running Windows 10 version 21H1

**Comment by dimaguy** [comment]
Bug also on Windows 11 21H2, also sometimes keystrokes(like tab) are also captured by the window instead of the one I'm working on

**Comment by Sanakan8472** [comment]
Ah yes, the focus handling is tricky here. Removing `showOverlay = true;` in *OverlayWindow.cs* line 194 fixes the issue but might introuduce other problems. I'll have to investigate a bit to make a proper fix to handle all focus scenarios.
