### ISSUE TITLE
I would LOVE to see this integrated in Windows ❤

### ISSUE THREAD

**Issue by rezatitan7** [Sanakan8472/copy-dialog-lunar-lander#11]
Or even a way to disable tray app with auto start during Windows startup, so we can have it in the background all the time ❤.

**Comment by Sanakan8472** [comment]
Well I would LOVE to integrate this into Windows as well! One can dream right?
But starting during Windows startup should be possible, I'll have a look, how hard can it be?

**Comment by priyavrat-misra** [comment]
It's definitely a hard process, there are like 6 steps. /s

- Copy `CopyDialogLunarLander.exe`
- Open run (<kbd>win</kbd> + <kbd>r</kbd>)
- Type `shell:startup`
- Hit <kbd>Enter</kbd>
- Right click
- "Paste shortcut"

**Comment by rezatitan7** [comment]
I do a lot of file transfers to my HDDs and so far I've fallen in love with this cute little mini-game, if you only could add option to 'hide tray icon' and 'auto start during windows startup' that would be superb 🤍🤍🤍

**Comment by Sanakan8472** [comment]
@rezatitan7, @priyavrat-misra's steps should work for any kind of application but if that is not convenient enough, there is now a checkbox for that in the new 1.1. version. As for hiding the tray icon, this is not something I control. You can toggle that on and off by yourself, see [here](https://support.microsoft.com/en-us/windows/customize-the-taskbar-notification-area-e159e8d2-9ac5-b2bd-61c5-bb63c1d437c3) for example.

**Comment by rezatitan7** [comment]
Now this made my day, pure cuteness and beauty, thank you, you beautiful dev😊💕💕💕.

**Comment by rezatitan7** [comment]
@Sanakan8472 Although some apps like TranslucentTB have the ability to completely hide the tray icon, not just hiding it under "show hidden icons". I just wish you could add this feature too🤗.

**Comment by Sanakan8472** [comment]
Ah I see @rezatitan7 , I didn't know you wanted to completely hide the tray icon. As that would make it very hard to close the application I'd rather not do that as you wouldn't be able to turn it back on or change autostart settings etc. Letting the user move the icon to the hidden icons settings is probably the best compromise.

**Comment by rezatitan7** [comment]
@Sanakan8472 I would say it's no biggie, since I've been using Rainmeter for years, it has a hide tray icon option, If I want to close it completely, simply I can find it in the task manager, whenever I close it from task manager and reopen it, it shows the manage Rainmeter window again😊👌.
