### ISSUE TITLE
Pack all those dlls in one exe

### ISSUE THREAD

**Issue by zorikfx** [Sanakan8472/copy-dialog-lunar-lander#14]
Not really important, but I would like it to be one exe without those nasty dlls cluttering up my SSD. Shouldn't be too hard (and I did try doing this myself but I couldn't get it to compile, so I just packed it with Enigma Virtual Box)

**Comment by Sanakan8472** [comment]
Would it be fine to make it an installer instead? I haven't looked at it so far but the distribution mechanism certainly leaves much to be desired right now.

**Comment by zorikfx** [comment]
Maybe like a themed 7-zip SFX. That could work.
