### ISSUE TITLE
crashes right after opening - windows 11 22000.978

### ISSUE THREAD

**Issue by XxTWMLxX** [Sanakan8472/copy-dialog-lunar-lander#8]
running the exe opens the tray icon but clicking on the tray icon just opens a little white square box.
box has no text and the windows circle loading circle spins. dialog for close/wait to respond shows. 

then it closes the tray icon.  

running as admin or normal same symptoms.

**Comment by Sanakan8472** [comment]
Hi @XxTWMLxX ,
I have never tested Windows 11. Only two Windows 10 machines. I also have no logging capabilities to speak of built into the app so your only chance is to run the app from Visual Studio and see where is crashed.

**Comment by XxTWMLxX** [comment]
i got it to work, it still crashes on opening, 
i had to put the files in system32 folder directly. (wouldnt run from anywhere else on my system (win 11 pro) 

then prob didnt need next step but i made it auto run with admin privileges via a registry startup entry.
