### ISSUE TITLE
how to run this

### ISSUE THREAD

**Issue by matejkoo217** [Sanakan8472/copy-dialog-lunar-lander#9]

**Comment by Hellohi3654** [comment]
Download the zip from here
https://github.com/Sanakan8472/copy-dialog-lunar-lander/releases/latest
And run the file inside

**Comment by matejkoo217** [comment]
Witch one

**Comment by sammccants** [comment]
CopyDialogLunarLander.exe

**Comment by Sanakan8472** [comment]
Here is a direct link to the zip: [copy-dialog-lunar-lander-v1.0.zip](https://github.com/Sanakan8472/copy-dialog-lunar-lander/releases/download/v1.0/copy-dialog-lunar-lander-v1.0.zip).
Extract it to any folder and run `CopyDialogLunarLander.exe`.
